name: basic
run-name: postsubmit run

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  bazel-build:
    strategy:
      matrix:
        includescanner: ["goma", "clangscandeps"]
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Get Bazel
        uses: bazel-contrib/setup-bazel@b388b84bb637e50cdae241d0f255670d4bd79f29
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      # Checkout the depot tools they are needed by the goma repository
      - name: Checkout depot tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Update PATH
        run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH

      - name: Bazel Build
        run: bazel build --config=${{ matrix.includescanner }} --//:use_android_glibc=true //:artifacts.tar
